#!/usr/bin/env python3
"""Scaffold a standard QA automation project (Playwright-Web or Appium-App POM).

Lays down the canonical folder structure + the static boilerplate (pom.xml, Makefile,
suites, configs, .env.example, .gitignore, sitemap schema) for the chosen platform, with
the project's package/name/URL substituted in. The Java framework classes + the example
feature are then generated by the `scaffold-method` skill following the platform
design-pattern — this script only creates the deterministic skeleton + config.

Static templates live in  templates/scaffold/<platform>/  (relative to the plugin root).
Token substitution in every copied file:
    __GROUP__      maven groupId            (e.g. com.example)
    __ARTIFACT__   maven artifactId         (e.g. myapp-web-automation)
    __PKG__        base java package        (e.g. com.example.app)
    __PKG_PATH__   package as a path        (com/example/app)
    __NAME__       human project name       (e.g. MyApp Web)
    __BASE_URL__   app base url             (e.g. https://app.example.com/)
    __ID_URL__     identity/login origin    (web; e.g. https://id.example.com/)
    __HOME_PATH__  home route               (web; e.g. /home)

Usage:
    python3 scaffold.py --platform web --package com.example.app --name "MyApp Web" \
        --base-url https://app.example.com/ [--id-url ...] [--home-path /home] [--force]

Exit codes: 0 ok · 2 bad args · 3 refused (project already exists, no --force).
Never overwrites your code: refuses if pom.xml or src/ already exist unless --force.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

PLUGIN_ROOT = Path(os.environ.get("CLAUDE_PLUGIN_ROOT", Path(__file__).resolve().parent.parent))


# Java package dirs created (empty, with .gitkeep) so the structure is visible; the
# scaffold-method skill fills these with the framework classes + the example feature.
TREE = {
    "web": {
        "main": ["config", "core", "flows", "utils", "models", "sitemap", "report",
                 "screens/base", "screens/auth", "screens/home"],
        "test": ["base", "tests", "tests/auth", "smoke/auth", "smoke/home",
                 "regressions/auth", "regressions/home"],
    },
    "app": {
        "main": ["appium", "actions", "models", "utils", "sitemap",
                 "screens/base", "screens/auth", "screens/home"],
        "test": ["base", "tests", "tests/auth", "smoke/home", "regression/home"],
    },
}

# Non-source dirs every project gets.
COMMON_DIRS = ["sitemap/screens", "plans", "results", "docs"]


def subst(text: str, tok: dict) -> str:
    for k, v in tok.items():
        text = text.replace(k, v)
    return text


def copy_templates(src_root: Path, dst_root: Path, tok: dict, force: bool) -> list[str]:
    """Copy every file under src_root into dst_root, substituting tokens in path + content."""
    written = []
    for src in sorted(src_root.rglob("*")):
        if src.is_dir():
            continue
        rel = subst(str(src.relative_to(src_root)), tok)
        # `gitignore` template → `.gitignore` (append-or-create handled by caller marker)
        is_gitignore = rel == "gitignore"
        target = dst_root / (".gitignore" if is_gitignore else rel)
        raw = src.read_text(encoding="utf-8")
        content = subst(raw, tok)
        if is_gitignore and target.exists() and not force:
            existing = target.read_text(encoding="utf-8")
            if "qa-scaffold" not in existing:
                target.write_text(existing.rstrip() + "\n\n" + content, encoding="utf-8")
                written.append(str(target.relative_to(dst_root)) + " (appended)")
            continue
        if target.exists() and not force:
            written.append(str(target.relative_to(dst_root)) + " (kept — exists)")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(str(target.relative_to(dst_root)))
    return written


def make_tree(dst: Path, platform: str, pkg_path: str) -> list[str]:
    made = []
    for d in COMMON_DIRS:
        (dst / d).mkdir(parents=True, exist_ok=True)
    spec = TREE[platform]
    for scope, base in (("main", f"src/main/java/{pkg_path}"), ("test", f"src/test/java/{pkg_path}")):
        for leaf in spec[scope]:
            p = dst / base / leaf
            p.mkdir(parents=True, exist_ok=True)
            keep = p / ".gitkeep"
            if not any(c for c in p.iterdir() if c.name != ".gitkeep"):
                keep.write_text("", encoding="utf-8")
            made.append(str((Path(base) / leaf)))
    return made


def main(argv=None):
    ap = argparse.ArgumentParser(description="Scaffold a standard QA automation project")
    ap.add_argument("--platform", required=True, choices=["web", "app"])
    ap.add_argument("--package", required=True, help="base java package, e.g. com.example.app")
    ap.add_argument("--name", default="", help="human project name (default derived from package)")
    ap.add_argument("--group", default="", help="maven groupId (default = package minus last segment)")
    ap.add_argument("--artifact", default="", help="maven artifactId (default derived from name)")
    ap.add_argument("--base-url", default="https://app.example.com/", help="app base URL")
    ap.add_argument("--id-url", default="https://id.example.com/", help="identity/login origin (web)")
    ap.add_argument("--home-path", default="/home", help="home route (web)")
    ap.add_argument("--dir", default=".", help="target project dir (default: cwd)")
    ap.add_argument("--force", action="store_true", help="overwrite even if a project exists")
    args = ap.parse_args(argv)

    dst = Path(args.dir).resolve()
    dst.mkdir(parents=True, exist_ok=True)

    if not args.force and ((dst / "pom.xml").exists() or (dst / "src").is_dir()):
        print(f"[scaffold] REFUSED: a project already exists at {dst} (pom.xml/src present). "
              f"Use --force to scaffold anyway (will not delete your files, only add/keep).")
        return 3

    pkg = args.package.strip()
    if not pkg.replace(".", "").isalnum():
        print(f"[scaffold] bad --package '{pkg}' (use dotted java package, e.g. com.example.app)")
        return 2
    pkg_path = pkg.replace(".", "/")
    group = args.group.strip() or (".".join(pkg.split(".")[:-1]) or pkg)
    name = args.name.strip() or pkg.split(".")[-1].capitalize()
    artifact = args.artifact.strip() or (name.lower().replace(" ", "-") + "-automation")

    tok = {
        "__GROUP__": group, "__ARTIFACT__": artifact, "__PKG__": pkg, "__PKG_PATH__": pkg_path,
        "__NAME__": name, "__BASE_URL__": args.base_url.strip(),
        "__ID_URL__": args.id_url.strip(), "__HOME_PATH__": args.home_path.strip(),
    }

    src_root = PLUGIN_ROOT / "templates" / "scaffold" / args.platform
    if not src_root.is_dir():
        print(f"[scaffold] no templates for platform '{args.platform}' at {src_root}")
        return 2

    print(f"[scaffold] {args.platform} project → {dst}")
    print(f"[scaffold]   package={pkg}  group={group}  artifact={artifact}  name={name}")
    dirs = make_tree(dst, args.platform, pkg_path)
    files = copy_templates(src_root, dst, tok, args.force)

    # Shared sitemap schema (one source of truth for both platforms).
    schema_src = PLUGIN_ROOT / "templates" / "sitemap" / "SCHEMA.md"
    schema_dst = dst / "sitemap" / "SCHEMA.md"
    if schema_src.is_file() and (args.force or not schema_dst.exists()):
        schema_dst.parent.mkdir(parents=True, exist_ok=True)
        schema_dst.write_text(schema_src.read_text(encoding="utf-8"), encoding="utf-8")
        files.append("sitemap/SCHEMA.md")
    # Seed the generated aggregate so the tree is complete (regenerated by gen_sitemap.py).
    seed = dst / "sitemap" / "sitemap.json"
    if not seed.exists():
        seed.write_text('{"screens": {}}\n', encoding="utf-8")
        files.append("sitemap/sitemap.json (seed)")

    print(f"[scaffold] created {len(dirs)} source dirs + {len(files)} boilerplate files:")
    for f in files:
        print(f"           {f}")
    print("[scaffold] NEXT: the scaffold-method skill now generates the Java framework + the "
          "example 'auth/login' feature for this platform, then runs build-verify (mvn test-compile).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
